apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-img
spec:
  selector: 
    matchLabels: 
      app: go-app-img
  replicas: 2   
  template: 
    metadata:
      labels: 
        app: go-app-img
    spec:
      containers:
      - name: go-app-img
        image: rinu8340/go-app-img:latest
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: go-app-img
spec:
  selector:
    app: go-app-img
  ports:
    - protocol: TCP
      port: 3000          
